import type { Metadata } from 'next'

import { fetchTokenIssuedCounts } from '@/services/server/UserServerService'
import { AreaChartCostom } from '@/components/Charts/LinerAreaChart'
import { BarChartCustom, BarChartHorizontalCustom } from '@/components/Charts/BarChart'
import { PieChartCustom } from '@/components/Charts/PieChart'
import { ChartConfig } from '@/components/ui/chart'
import { IChartSeriesProps } from '@/types/components/ChartType'
import { IUserChartProps } from '@/types/apps/UserType'

/**
 * 정적 메타 정보 생성
 */
export const metadata: Metadata = {
    title: "now2woy's Portfolio",
    description: "now2woy's Portfolio Generated by create next app"
}

/**
 * 바 또는 선, 영역 차트 Config
 */
const chartConfig: ChartConfig = {
    dailyCount: {
        label: '발행 수',
        color: 'var(--color-blue-600)'
    }
}

/**
 * 개별 데이터 계열의 정보 Props
 */
const chartSeries: IChartSeriesProps[] = [
    {
        key: 'dailyCount',
        fillColor: 'var(--color-blue-500)',
        strokeColor: 'var(--color-blue-500)'
    }
]

/**
 * 메인 화면
 * @returns
 */
const Home = async () => {
    const data = await fetchTokenIssuedCounts()

    return (
        <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
            <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-balance">now2woy&apos;s Portfolio</h1>
            <div className="grid auto-rows-min gap-4 md:grid-cols-2 lg:grid-cols-3">
                <AreaChartCostom
                    title="Access Token 발행 수"
                    description="지난 7일간의 액세스 토큰 발행 수"
                    chartData={data}
                    chartConfig={chartConfig}
                    xDataKey="issuedDe"
                    chartSeries={chartSeries}
                />
                <BarChartCustom
                    title="Access Token 발행 수"
                    description="지난 7일간의 액세스 토큰 발행 수"
                    chartData={data}
                    chartConfig={chartConfig}
                    xDataKey="issuedDe"
                    chartSeries={chartSeries}
                />
                <BarChartHorizontalCustom
                    title="Access Token 발행 수"
                    description="지난 7일간의 액세스 토큰 발행 수"
                    chartData={data}
                    chartConfig={chartConfig}
                    xDataKey="dailyCount"
                    yDataKey="issuedDe"
                    chartSeries={chartSeries}
                />
                <PieChartCustom<IUserChartProps>
                    title="일별 토큰 발행 수"
                    description="지난 7일간의 액세스 토큰 발행 수"
                    chartData={data}
                    dataKey="dailyCount"
                    nameKey="issuedDe"
                    label="Daily Count"
                />
            </div>
        </div>
    )
}

export default Home
