import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "now2woy's Portfolio",
  description: "now2woy's Portfolio Generated by create next app",
};

const Home = () => {
  
  return (
    <div className="p-6">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-balance">now2woy&apos;s Portfolio</h1>
      <p className="text-muted-foreground text-xl leading-7 [&:not(:first-child)]:mt-6">포트폴리오 메인 화면 입니다.</p>
    </div>
  )
}

export default Home;