pipeline {
	agent any
	
	environment {
		REGISTRY = "localhost:5000"
		IMAGE_NAME = "now2woy/portfolio-default-service"
		IMAGE_TAG = "${GIT_COMMIT}"
		DOCKER_HOST = "unix:///var/run/docker.sock"
		REGISTRY_USER = credentials('DOCKER_REGISTRY_USER')
		REGISTRY_PASS = credentials('DOCKER_REGISTRY_PASS')
		PORTFOLIO_DB_URL = credentials('PORTFOLIO_DB_URL')
		PORTFOLIO_DB_ID = credentials('PORTFOLIO_DB_ID')
		PORTFOLIO_DB_PW = credentials('PORTFOLIO_DB_PW')
		PORTFOLIO_JWT_KEY = credentials('PORTFOLIO_JWT_KEY')
		K8S_NAMESPACE = "portfolio"
		K8S_DEPLOYMENT = "backend-default-service"
	}
	
	stages {
		stage('Checkout') {
			steps {
				git branch: 'main',
				url: 'https://github.com/now2woy/portfolio-project.git',
				credentialsId: 'GIT-HUB-NOW2WOY'
			}
		}
		
		stage('Prepare') {
			steps {
				dir('apps/backend-default-service') {
					sh 'chmod +x gradlew'
				}
			}
		}

		stage('Build JAR') {
			steps {
				dir('apps/backend-default-service') {
					sh './gradlew clean build -x test'
				}
			}
		}
		
		stage('Docker Login') {
			steps {
				sh """
					echo "${REGISTRY_PASS}" | docker login ${REGISTRY} -u "${REGISTRY_USER}" --password-stdin
				"""
			}
		}
		
		stage('Build & Push Image') {
			steps {
				dir('apps/backend-default-service') {
					sh """
						# 빌드 (commit hash 태그로)
						docker build \
							--build-arg DB_URL=${PORTFOLIO_DB_URL} \
							--build-arg DB_USERNAME=${PORTFOLIO_DB_ID} \
							--build-arg DB_PASSWORD=${PORTFOLIO_DB_PW} \
							--build-arg JWT_SECRET_KEY=${PORTFOLIO_JWT_KEY} \
							-t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} .
						
						# latest 태그도 추가
						docker tag ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY}/${IMAGE_NAME}:latest
						
						# 두 개 다 푸시
						docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
						docker push ${REGISTRY}/${IMAGE_NAME}:latest
					"""
				}
			}
		}
		
		stage('Deploy to Kubernetes') {
			steps {
				sh """
					# 커밋 해시 태그 기준으로 배포 (히스토리 추적용)
					kubectl set image deployment/${K8S_DEPLOYMENT} ${K8S_DEPLOYMENT}=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -n ${K8S_NAMESPACE}
					
					kubectl rollout status deployment/${K8S_DEPLOYMENT} -n ${K8S_NAMESPACE}
				"""
			}
		}
	}
	
	post {
		success {
			echo '✅ 배포 성공!'
		}
		
		failure {
			echo '❌ 빌드/배포 실패!'
		}
	}
}
